In [1]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度

In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

我们可以通过张量的shape属性来访问张量的形状和张量中元素的总数

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

要改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数

In [5]:
x=x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其他常量或者从特定分布中随机采样的数字

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [8]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

常见的标准算术运算符都可以被升级为按元素运算

In [9]:
x=torch.tensor([1.0,2,4,5])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([3., 4., 6., 7.]),
 tensor([-1.,  0.,  2.,  3.]),
 tensor([ 2.,  4.,  8., 10.]),
 tensor([0.5000, 1.0000, 2.0000, 2.5000]),
 tensor([ 1.,  4., 16., 25.]))

我们也可以把多个张量连结在一起

In [11]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

这里dim决定方向，例如上个案例，X和Y都是二维张量，所以有两个方向，dim=0就是沿着行的方向拼接，dim=1就是沿着列

通过逻辑运算符构建二元张量

In [12]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量所有元素进行求和会产生一个只有一个元素的张量

In [13]:
X.sum()

tensor(66.)

即使形状不同，我们仍然可以用广播机制(broadcasting mechanism)来执行按元素操作

In [14]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

通过指定索引来将元素写入矩阵

In [16]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能会导致新结果内存分配

In [18]:
before=id(Y)
Y=X+Y
id==before

False

执行原地操作

In [19]:
z=torch.zeros_like(Y)
print('id(z):',id(z))
z[:]=X+Y
print('id(z):',id(z))

id(z): 3051584511088
id(z): 3051584511088


如果在后续计算中没有重复使用X，我们也可以用X[:]=X+Y或X+=Y来减少后续的内存开销

In [20]:
before=id(X)
X+=Y
id(X)==before

True

转换为NumPy张量

In [21]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为Python标量，例如这里的item将张量转换为py中的普通数字

In [22]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)