标量由只有一个元素的张量表示

In [1]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

你可以将向量视为标量值组成的列表

In [2]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

访问张量的长度

In [4]:
len(x)

4

只有一个轴的张量，形状就只有一个元素

In [5]:
x.shape

torch.Size([4])

通过指定两个分量m和n来创建一个形状为m*n的矩阵

In [6]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置，就是沿着对角线对折

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵(symmetric matrix) A等于其转置：A=A.T

In [9]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构

In [11]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

注意看上述有三个[][][]，三维矩阵

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都是相同形状的张量

In [12]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()#通过分配新内存，将A的一个副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵按元素的乘法称为哈达玛积,注意看，这里和矩阵的乘法不一样，就是单纯的两数相乘

In [13]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [15]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape#就是X中的每个元素都加上a这个标量

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算其元素的和

In [16]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [20]:
A=torch.arange(20*2).reshape(2,5,4)
A.shape,A.sum(),A

(torch.Size([2, 5, 4]),
 tensor(780),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]))

指定求和汇总张量的轴

In [19]:
A_sum_axis0=A.sum(axis=0)#按照第一个维度求和，就是把上下两个矩阵加起来
A_sum_axis0,A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [22]:
A_sum_axis1=A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [24]:
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

一个与求和相关的量是平均值

In [26]:
A=torch.arange(40,dtype=torch.float32).reshape(2,5,4)
A.mean(),A.sum()/A.numel()#这里mean的输入必须是浮点数或复数类型

(tensor(19.5000), tensor(19.5000))

In [27]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

计算总和或均值时保持轴数不变

In [28]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

通过广播将A除以sum_A

In [29]:
A/sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

某个轴计算A元素的累计综合

In [30]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

点积是相同位置的按元素乘积的和

In [31]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [32]:
torch.sum(x*y)

tensor(6.)

矩阵向量积Ax是一个长度为m的列向量，也要满足A:(s,t)，x:(t,)

In [36]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,x.shape,torch.mv(A,x)#mv对应matrix和vector

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

矩阵乘法AB

In [37]:
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根，norm

In [38]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

L1范数是向量元素的绝对值求和

In [39]:
torch.abs(u).sum()

tensor(7.)

矩阵的佛罗贝尼乌斯范数(Frobenius norm)是矩阵元素的平方和的平方根

In [40]:
torch.norm(torch.ones(4,9))

tensor(6.)

总结：norm就是元素平方和的平方根