假设我们想对函数y=2x.T*x关于列向量x求导

In [2]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

在我们计算y关于x的梯度之前，我们需要一个地方来存储梯度

In [3]:
x.requires_grad_(True)#告诉pytorch我后面需要求梯度
x.grad

In [4]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来自动计算y关于x每个分量的梯度，backward要求输入的tensor是一个标量

In [5]:
y.backward()#自动进行求导，并将梯度放在x.grad中
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad==x*4

tensor([True, True, True, True])

现在计算x的另一个函数

In [7]:
#在默认情况下，PyTorch会累计梯度，我们需要清除之前的值
x.grad.zero_()#清除
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

深度学习中，我们的目的是批量中每个样本单独计算的偏导数之和

In [8]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

将某些计算移动到记录的计算图之外

In [9]:
x.grad.zero_()
y=x*x
u=y.detach()#把y从计算图中摘下，得到一个不再参与梯度计算的tensor，在后续的梯度计算中，u就是一个标量
z=u*x

z.sum().backward()
x.grad==u

tensor([True, True, True, True])